### ISSUE TITLE
`combine` should allow specifying a mapper

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-mapper#15]
Just like `wrap` and `group` can specify a mapper to call out to, `combine` should allow one to specify a mapper to reuse:

``` ruby
combine :data, on: { id: :parent_id }, mapper: DataMapper
```

We should also make sure that a single-element combine remains possible:

``` ruby
combine :source, on: { id: :parent_id }, mapper: SourceMapper, type: :hash
# Results in a single-element passed through the SourceMapper.
```

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
