### ISSUE TITLE
A more helpful error when model constructor arity is incorrect

### ISSUE THREAD

**Issue by jaredbeck** [rom-rb/rom-mapper#16]
From what I can tell, the [arity](http://ruby-doc.org/core-2.2.0/Method.html#method-i-arity) of the model's constructor should be exactly `1`.  Is this correct?  

The arity requirement is documented, though not in those exact words.

> Domain entities are responsible for instantiating their objects from mapper-provided hashes.
> http://rom-rb.org/guides/basics/mappers/#applying-mappers-to-relations

When the arity is incorrect, the following exception is raised:

```
Transproc::MalformedInputError:

Failed to call_function map_array with [[{...}]] - 
Failed to call_function constructor_inject with [{...}] - 
wrong number of arguments (1 for 0)

# gems/transproc-0.3.2/lib/transproc/class.rb:30:in `initialize'
# gems/transproc-0.3.2/lib/transproc/class.rb:30:in `new'
# gems/transproc-0.3.2/lib/transproc/class.rb:30:in `constructor_inject'
# gems/transproc-0.3.2/lib/transproc/function.rb:47:in `call'
# gems/transproc-0.3.2/lib/transproc/function.rb:47:in `call'
# gems/transproc-0.3.2/lib/transproc/array.rb:50:in `block in map_array!'
# gems/transproc-0.3.2/lib/transproc/array.rb:50:in `map!'
# gems/transproc-0.3.2/lib/transproc/array.rb:50:in `map_array!'
# gems/transproc-0.3.2/lib/transproc/array.rb:41:in `map_array'
# gems/transproc-0.3.2/lib/transproc/function.rb:47:in `call'
# gems/transproc-0.3.2/lib/transproc/function.rb:47:in `call'
# gems/rom-mapper-0.2.0/lib/rom/mapper.rb:95:in `block in call'
```

There's nothing incorrect about this error message, but I wonder if `rom-mapper` could be more helpful.

Could the arity of the model's constructor be checked, and a more helpful error raised, e.g. `ROM::Mapper::InvalidModelError`?

**Comment by solnic** [comment]
We could do the check and raise an error during mapper definition inside [Model DSL](https://github.com/rom-rb/rom-mapper/blob/master/lib/rom/mapper/model_dsl.rb). The mapper only supports `:constructor_inject` with an attribute hash as the only argument so we can just check constructor arity and raise if it's > 1. So, yes, you are correct :)

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
