### ISSUE TITLE
polymorphic mappers

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-mapper#19]
There may be instances where it makes sense for a mapper to return a heterogeneous collection of results:

``` ruby
class UserMapper < ROM::Mapper
   # ...
   model do |attrs|
     attrs[:status] == 'active' ? User : InactiveUser
   end
end
```

This would let one pus behavioral differences down into the models, where they belong, without requiring the queries to work around potentially mixed data sets.

**Comment by solnic** [comment]
I'm moving away from mapping to models and pushing that responsibility to the domain layer, so mappers just convert relations into array of hashes (if needed) and model constructors turn hashes into specific objects (including aggregates).

Having said that - we can support this feature :joy:

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
