### ISSUE TITLE
Proposal for changing mapper behaviour

### ISSUE THREAD

**Issue by AMHOL** [rom-rb/rom-mapper#24]
## Explaination

I've just gotten around to using rom-mapper and have found a few problems with the way I'd like to use it, perhaps I am missing some integral concepts, or just using it the wrong way, however, I think that what I'm doing is probably a common use-case for rom-mapper and I have seen various people flag up the same, or similar, issues.
## Problems (?)

Below is a list of the problems I have with the current behaviour of rom-mapper.
#### Blocks passed to attributes are bound to the DSL

Blocks that are passed to attributes are executed in the context of the DSL, I think they should be executed in context of the mapper, this would allow any dependencies passed to the mapper to be used in the block context, this would require some re-jigging to work smoothly, i.e. the default header and processor could be configured rather than injected.
#### Reject keys seems to be the first operation

Rejecting keys (Transproc `:accept_keys`) seems to be the first operation in transformers, and it whitelists the input tuple keys - this seems strange. I think it would be simpler if `reject_keys` were the last operation and used the attribute names as the whitelist. This would also suit `reject_keys` being enabled by default, so the output will only ever contain attribute names that you specify (by default).
#### From could take multiple keys

Currently, you can only pass one key to the `from` option, it would be good to pass multiple keys and compose new attributes from multiple input values.
#### From renames keys

Passing the `from` option currently moves key-value pairs in the input, this means that you can't create attributes from the same input value multiple times. Rather than renaming (and deleting the existing value), we could just yield the values from the keys passed to from in (possibly a variation of) Transproc `map_value`. This would keep the existing key-value pairs in-tact, however, they would be rejected by the final `reject_keys` (Transproc `accept_keys`) operation unless explicitly specified as an attribute.
## Result

If the above were implemented, we could use mappers like so:

``` ruby
class MyMapper < ROM::Mapper
  attr_reader :hasher
  private :hasher

  configure do |config|
    # These are just the defaults, but this is 
    # just an example of how configuration could work
    config.header = ROM::Mapper.header
    config.processor = :transproc
  end

  # We can now use DI as we can configure header and 
  # processor freeing up the initializer, we can also initialize
  # with new rather than build (like it matters lol)
  def initialize(hasher)
    @hasher = hasher
  end

  attribute(:first_name, from: :name) { |name| name.to_s.split(' ').first }
  attribute(:last_name,  from: :name) { |name| name.to_s.split(' ').last }
  attribute(:email,      from: :email_address)
  # We can now use dependencies in blocks as they are executed
  # in the mapper context
  attribute(:password_salt) { hasher.generate_salt }
  attribute(:password_hash, from: [:password, :password_salt]) do |password, salt|
    hasher.hash_secret(password, salt)
  end
end
```

Now the mapper would perform the transformations:

``` ruby
# SETUP
hasher = Class.new do
  def self.generate_salt
    'WYEG*&REGY&ERGG**&%UFV*YFBH$F'
  end

  def self.hash_secret(password, salt)
    'F&^*WEK)WFJ"$WF)J$FJ)JGHGWH)G$*GH)W$G'
  end
end
module Transproc
  module CustomHashTransformations
    extend Registry
    def self.map_value_from(hash, key, from_keys, fn)
      hash.merge(key => fn[*hash.values_at(*from_keys)])
    end

    def self.map_value_from!(hash, key, from_keys, fn)
      hash.update(key => fn[*hash.values_at(*from_keys)])
    end

    (methods - Registry.instance_methods - Registry.methods)
      .each { |name| Transproc.register name, t(name) }
  end
end
# END SETUP

# This is for a single tuple for simplicity
input = {
  name: 'John Smith',
  email_address: 'john.smith@mysite.com',
  password: '5up3r53cur3'
}
input = Transproc[
  :map_value_from, :first_name, [:name], ->(name) { name.to_s.split(' ').first }
][input]
# => {
#   :name          => "John Smith",
#   :email_address => "john.smith@mysite.com",
#   :password      => "5up3r53cur3",
#   :first_name    => "John"
# }
input = Transproc[
  :map_value_from, :last_name, [:name], ->(name) { name.to_s.split(' ').last }
][input]
# => {
#   :name          => "John Smith",
#   :email_address => "john.smith@mysite.com",
#   :password      => "5up3r53cur3",
#   :first_name    => "John",
#   :last_name     => "Smith"
# }
input = Transproc[
  :map_value_from, :email, [:email_address], Transproc[:identity]
][input]
# => {
#   :name          => "John Smith",
#   :email_address => "john.smith@mysite.com",
#   :password      => "5up3r53cur3",
#   :first_name    => "John",
#   :last_name     => "Smith",
#   :email         => "john.smith@mysite.com"
# }
input = Transproc[
  :map_value_from, :password_salt, [], -> { hasher.generate_salt }
][input]
# => {
#   :name          => "John Smith",
#   :email_address => "john.smith@mysite.com",
#   :password      => "5up3r53cur3",
#   :first_name    => "John",
#   :last_name     => "Smith",
#   :email         => "john.smith@mysite.com",
#   :password_salt => "WYEG*&REGY&ERGG**&%UFV*YFBH$F"
# }
input = Transproc[
  :map_value_from,
  :password_hash,
  [:password, :password_hash],
  ->(password, salt) { hasher.hash_secret(password, salt) }
][input]
# => {
#   :name          => "John Smith",
#   :email_address => "john.smith@mysite.com",
#   :password      => "5up3r53cur3",
#   :first_name    => "John",
#   :last_name     => "Smith",
#   :email         => "john.smith@mysite.com",
#   :password_salt => "WYEG*&REGY&ERGG**&%UFV*YFBH$F",
#   :password_hash => "F&^*WEK)WFJ\"$WF)J$FJ)JGHGWH)G$*GH)W$G"
# }
input = Transproc[
  :accept_keys,
  [:first_name, :last_name, :email, :password_hash, :password_salt]
][input]
# => {
#   :first_name    => "John",
#   :last_name     => "Smith",
#   :email         => "john.smith@mysite.com",
#   :password_hash => "F&^*WEK)WFJ\"$WF)J$FJ)JGHGWH)G$*GH)W$G",
#   :password_salt => "WYEG*&REGY&ERGG**&%UFV*YFBH$F"
# }
```

**Comment by daniels** [comment]
I like this. I've been using a custom `:copy_keys` transformation to extract multiple values from the same input field, but keeping the original in the output by default would simplify that.

I would add that when using steps with `reject_keys true`, it applies to every step, so you have to explicitly name all attributes over and over again in each step to keep them. If/When altering the behaviour of `reject_keys` I would suggest also making it a per step option, or being applied after the last step only.

**Comment by solnic** [comment]
Blocks evaluating in the context of the mappers sounds good. And I am definitely for unifying object construction within all ROM gems and use some IoC/DI internally to allow simple injection wherever and whenever we want.

`rejecting_keys` first makes things faster as there are less object allocations during any other potential transformations but if it causes weird behavior then it's not worth to do it like that.

I'm not sure if making `reject_keys` a dependency of `rename_keys` a good idea, I would say you should use 2-step processing if you want to reflect on original values first, then rename keys, renaming means you take `:a` and make it `:b` rather than *adding* `:b`. I think current semantics of `rename_keys` are correct.

`from` accepting multiple keys sounds good, it would require a new attribute type but on the surface it could be the same API for a single key and multi-keys.

**Comment by AMHOL** [comment]
@solnic I'm not sure what you mean RE `making reject_keys a dependency of rename_keys`?

My suggestion was to move it to the last operation and used the names for the defined attributes, so:

```ruby
attribute :id
attribute :name
```
Would make the last operation a Transproc `accept_keys` with the keys set to `:id` and `:name`
```

**Comment by solnic** [comment]
@AMHOL "dependency" in the sense that you gotta use it in order to prevent having left-overs after renaming (assuming it'd work in the way you suggested, which I think it shouldn't)

Rejecting keys by default has perf impact, let's also not forget about that, but more benchmarks should be done to verify that. It also makes no sense to reject keys when data are coming from trusted sources like your relations.

**Comment by AMHOL** [comment]
@solnic Ahh I get you. Seems a little strange to me that the mapper would make assumptions about the input though. I think it would be more intuitive if the mapper output only ever represented the attributes that the mapper defines, not sure about implementing a change in behaviour like that though.

**Comment by aflatter** [comment]
@AMHOL I have encountered all the issues you list, except the evaluate-block-within-mapper one. I think your proposed change would be a step in the right direction. It would make transformation of parameterized attribute names a lot easier, e.g. records with translated fields:

```ruby
class ProductMapper < ROM::Mapper
  attr_reader :locale

  def initialize(locale)
    @locale = locale
  end

  attribute(:title, from: -> { :"title_#{locale}" })
end
```

An API like this would probably delay building the transproc graph until the mapper is actually called, which is bad. Something like the following could work, though an additional block is required:

```ruby
class ProductMapper < ROM::Mapper
  attr_reader :locale

  def initialize(locale)
    @locale = locale

    build # evaluates the mapper block
  end

  mapper do
    attribute(:title, from: -> { :"title_#{locale}" })
  end
end
```

Mapper instances could then be cached. Let me know what you think.

**Comment by solnic** [comment]
I'm getting a feeling that people would like to put way too much domain-specific logic to mappers. I remember discussing the parameterized attribute feature few months ago. It's questionable whether this kind of logic belongs to the mapping layer or to your domain layer. I'm leaning towards the latter, actually.

Remember that every time you implement domain-specific functionality within mappers you couple your application to ROM, not sure if it's a smart decision.

You could resolve your localized values with your own object, easily:

``` ruby
Book = Struct.new(:title_en, :title_es, :locale) do
  def title
    self[:"#{title}_#{locale}"]
  end
end
```

This is way simpler than more complicated mapping layer, not to mention that it would make rom more complex wrt setup and building up mappers.

It's interesting to see what people are trying to do with mappers but we should be careful so that we won't turn mappers into hammers and look at everything as if it was a nail.

**Comment by aflatter** [comment]
@solnic I sympathize with your point and my scenario should probably not become a "best practice". My proposal stems from the fact that it simplifies an urgently needed refactoring in our application. I'll think about alternatives.

**Comment by solnic** [comment]
@aflatter I hear you. I won't be against it if we can support this feature w/o complicating rom too much
