### ISSUE TITLE
model dsl modify constructor signature of model class

### ISSUE THREAD

**Issue by mmeeoorroo** [rom-rb/rom-mapper#30]
Assume we have an model `Entities::Product` without any constructor, or a constructor without param:

```ruby
module Entities
  class Product
    attr_accessor :name, :id, :price, :category

    # def initialize
    # 
    # end
  end
end
```

and a mapper:

```ruby
require 'rom'
require 'rom-mapper'

module Mappers
  class Product < ROM::Mapper
    symbolize_keys true
    reject_keys true

    model name: Entities::Product.name

    attribute :name
    attribute :price
    attribute :category
    attribute :id
  end
end
```

here we can create an product instance normally using its constructor:

```ruby
p1 = Entities::Product.new
```

or using rom-mapper

```ruby
input = [
    {
        'id' => 'id1',
        'name' => 'product mot',
        'price' => 12.0,
        'category' => 'mobile'
    }
]
mapper = Mappers::Product.build
output = mapper.call input
puts output[0].inspect
```

After calling/using the mapper, we cannot create product instance using constructor-with-zero-param any more, but we can call the constructor with an param, e.g. an empty hash:

```
p2 = Entities::Product.new # this raises: ArgumentError: wrong number of arguments (0 for 1)
p3 = Entities::Product.new({}) # this is fine
```

Am I doing something wrong or this is the way rom-mapper work? Please give me some advise.

Thanks

**Comment by solnic** [comment]
You want `model(Entities::Product)`, otherwise it will generate a class for you under provided `name`.

**Comment by mmeeoorroo** [comment]
Thanks sonic.
I changed to `model(Entities::Product)` but now I get the error when call the mapper:

```ruby
input = [
    {
        'id' => 'id1',
        'name' => 'product mot',
        'price' => 12.0,
        'category' => 'mobile'
    }
]
mapper = Mappers::Product.build
output = mapper.call input # raises error ArgumentError: wrong number of arguments (1 for 0)
```

**Comment by solnic** [comment]
It expects the model to have a constructor which accepts attributes

**Comment by mmeeoorroo** [comment]
I've got it. Thanks solnic
