### ISSUE TITLE
guides link in README is wrong

### ISSUE THREAD

**Issue by joevandyk** [rom-rb/rom-mapper#32]
http://rom-rb.org/guides/basics/mappers/ doesn't exist, but is mentioned in README

**Comment by hmadison** [comment]
See http://www.rubydoc.info/gems/rom-mapper/0.2.0/ROM/Mapper/AttributeDSL for the same info

**Comment by joevandyk** [comment]
https://github.com/rom-rb/rom-mapper/pull/34 fixes it.
