### ISSUE TITLE
Strange behaviour when both symbolize_keys=true and reject_keys=true

### ISSUE THREAD

**Issue by mmeeoorroo** [rom-rb/rom-mapper#35]
When we enable both `symbolize_keys` and `reject_keys`, it also rejects any string key

```ruby
class MyMapper < ROM::Mapper
  symbolize_keys true
  reject_keys true

  attribute :id
  attribute :name
end

m = MyMapper.build

# This works as expected
m.call([{'id' => 1, 'name' => 'John'}])
#  [{:id=>1, :name=>"John"}]


# These two calls reject `name`
m.call([{'id' => 1, name: 'John'}])
m.call([{'id' => 1, :name => 'John'}])
# => [{:id=>1}]
```

It should not reject `name` or I don't understand correctly. Please help to clarify.

Thanks

**Comment by drinks** [comment]
It tends to expect string keys in my experience. You could supply the 'from: :name' option to make it work.

**Comment by AMHOL** [comment]
@mmeeoorroo this is a known issue, `symbolize_keys` will only accept string keys and convert them to symbols, this should be improved when someone has the time to do it

**Comment by mmeeoorroo** [comment]
@drinks @AMHOL Thanks guys. I thought it will symbolize string-keys and leave symbol-keys as they are.

**Comment by mmeeoorroo** [comment]
@drinks I added `from: :name` but it didn't work
