### ISSUE TITLE
Feature request: DSL to remove attribute from list

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-mapper#41]
I know, there is `reject_keys true` in Mapper, but it requires to define all attributes. It behaves like `whitelist`.

But sometimes it's wanted to pass all attributes, with some changes, and without specific attribute.
As I know, there is no way to define `blacklist` attributes in mapper.

`without_attribute` or `without` DSL method would be cool

**Comment by Kukunin** [comment]
actually, I've found [here](http://www.rubydoc.info/gems/rom-mapper/0.3.0/ROM%2FMapper%2FAttributeDSL%3Aexclude). But why is it private API?

**Comment by solnic** [comment]
@Kukunin mistake in docs

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
